spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      platform: h2
      mode: always
